version: "3.5"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports: 
      - 3008:9090
    extra_hosts: 
      - host.docker.internal:host-gateway
      - experiment-producer-host:${EXPERIMENT_PRODUCER_HOST}
      - notifications-service-host:${NOTIFICATIONS_SERVICE_HOST}
      - http-load-generator-host:${HTTP_LOAD_GENERATOR_HOST}
      - group1:${GROUP1_HOST}
      - group2:${GROUP2_HOST}
      - group3:${GROUP3_HOST}
      - group4:${GROUP4_HOST}
      - group5:${GROUP5_HOST}
      - group6:${GROUP6_HOST}
      - group7:${GROUP7_HOST}
      - group8:${GROUP8_HOST}
      - group9:${GROUP9_HOST}
      - group10:${GROUP10_HOST}
      - group11:${GROUP11_HOST}
      - group12:${GROUP12_HOST}
      - group13:${GROUP13_HOST}
      - group14:${GROUP14_HOST}
      - landau:${LANDAU_HOST}

  grafana: 
    image: grafana/grafana-enterprise
    ports: 
      - 3009:3000
    volumes: 
      - grafana-storage:/var/lib/grafana
    env_file: 
      ./grafana.env
    extra_hosts: 
      - host.docker.internal:host-gateway

volumes:
  prometheus-data:
  grafana-storage:
